@startuml
abstract class ProductTransformer
org.apache.camel.Processor <|-- ProductTransformer
ProductTransformer <|-- BookTransformer
ProductTransformer <|-- ElectronicsTransformer
ProductTransformer <|-- FashionTransformer
ProductTransformer <|-- CsvToBookTransformer
@enduml